/**
 * Enum defining the different types of Intents that can be returned by Actions.
 */
export const enum IntentType {
  Move = 'Move',
  Wait = 'Wait',
  ChangeArea = 'ChangeArea',
  DebugRevealMap = 'DebugRevealMap',
  DebugGodMode = 'DebugGodMode',
  DebugSpawnEntity = 'DebugSpawnEntity',
  ToggleTargeting = 'ToggleTargeting',
  MoveTarget = 'MoveTarget',
  FireAimed = 'FireAimed',
  MeleeAttack = 'MeleeAttack',
  PickUp = 'PickUp',
  Drop = 'Drop',
  EquipItem = 'EquipItem',
  UnequipItem = 'UnequipItem',
  ToggleInventory = 'ToggleInventory',
  ToggleFactions = 'ToggleFactions',
  ToggleSettings = 'ToggleSettings',
  UseAbility = 'UseAbility',
  ToggleEngineMode = 'ToggleEngineMode',
  TogglePause = 'TogglePause',
  SetRTwPSpeed = 'SetRTwPSpeed',
  ToggleInspect = 'ToggleInspect',
  MoveInspect = 'MoveInspect',
  ToggleRotated = 'ToggleRotated',
  Toggle3D = 'Toggle3D',
  SetZoomLevel = 'SetZoomLevel',
  StartDialogue = 'StartDialogue',
  SelectDialogueOption = 'SelectDialogueOption',
  CloseDialogue = 'CloseDialogue',
  ToggleQuests = 'ToggleQuests',
  ToggleInvestigation = 'ToggleInvestigation',
  ToggleDebug = 'ToggleDebug',
  ToggleDossier = 'ToggleDossier',
  DebugFastForwardSchemes = 'DebugFastForwardSchemes',
  DebugPromote = 'DebugPromote',
  Apply = 'Apply',
  Interact = 'Interact',
  Say = 'Say'
}
